spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
        - id: userConsumer
          #规则
          predicates:
            #根据请求路径匹配
            - Path=/user/**
          uri: lb://user-consumer
          #不去掉前缀
          filters:
            - StripPrefix=0
        - id: deptConsumer
          #规则
          predicates:
            #根据请求路径匹配
            - Path=/dept/**
          uri: lb://user-consumer
          #不去掉前缀
          filters:
            - StripPrefix=0
        - id: hobbyConsumer
          #规则
          predicates:
            #根据请求路径匹配
            - Path=/hobby/**
          uri: lb://user-consumer
          #不去掉前缀
          filters:
            - StripPrefix=0
        - id: userImg
          #规则
          predicates:
            #根据请求路径匹配
            - Path=/imgs/**
          uri: lb://user-service
          #去掉前缀
          filters:
            - StripPrefix=0
      #支持通过服务名定位服务
      discovery:
        locator:
          enabled: true
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #- "http://localhost:8080"
            #- "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
server:
  port: 8300

eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
